---
title: "My Simple Logistic Regression"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---

```{r, include=FALSE}
library(tidyverse)
library(ResourceSelection) 
library(car)
library(pander)

ratings <- read_csv("byui_ratings.csv")
prof <- read_csv("byui_professors.csv")
df <- ratings#left_join(prof, ratings, by = )
```

```{r}
letter_grades <- c("A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F")
grades <- c("A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "P", "INC", "Audit/No Grade", "WD", "Not sure yet")

ratings <- ratings %>% mutate(
  teacherGrade = factor(teacherGrade, levels = grades, labels = grades)
) %>% glimpse()

ratings$teacherGrade %>% unique()

ggplot(ratings, aes(teacherGrade)) +
  geom_bar(fill = "darkblue") +
  theme_minimal()

ggplot(ratings, aes(teacherGrade, rOverall)) +
  geom_boxplot()

ggplot(ratings, aes(teacherGrade, rOverall)) +
  geom_violin()

table(ratings$teacherGrade) %>% pander()
```

Grade Count

```{r}
table(ratings$teacherGrade) %>% pander()
```


Grade/Rating scatter plot

```{r}
ratings %>% 
  group_by(teacherGrade) %>% 
  summarize(
    ave_rating = mean(rOverall)
  ) %>% 
  ggplot(aes(teacherGrade, ave_rating)) +
  geom_point(color = "red", size = 3) +
  theme_bw() +
  labs(
    title = "Students Hate Getting Bad Grades",
    x = "Letter Grade",
    y = "Average Rating"
  )

ratings %>% 
  group_by(teacherGrade) %>% 
  summarize(
    ave_rating = mean(rOverall)
  ) %>% 
  ungroup() %>% 
  filter(teacherGrade %in% letter_grades) %>% 
  ggplot(aes(as.numeric(teacherGrade), ave_rating)) +
  geom_point(color = "red", size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(
    title = "Students Hate Getting Bad Grades",
    x = "Letter Grade",
    y = "Average Rating"
  )

ratings %>% 
  group_by(teacherGrade) %>% 
  summarize(
    ave_rating = mean(rOverall)
  ) %>% 
  ungroup() %>% 
  filter(!(teacherGrade %in% letter_grades)) %>% 
  ggplot(aes(teacherGrade, ave_rating)) +
  geom_point(color = "red", size = 3) +
  theme_bw() +
  labs(
    title = "Students Hate Getting Bad Grades",
    x = "Letter Grade",
    y = "Average Rating"
  )
```

Number of Grade Ratings

```{r}
ggplot(ratings, aes(teacherGrade)) +
  geom_bar(fill = "darkblue") +
  theme_minimal()
```


```{r}
glimpse(df)

df <- df %>% select(rEasy, rOverall) %>% rename(easy = rEasy, overall = rOverall)

df %>% ggplot(aes(easy, overall)) +
  geom_point() +
  stat_density_2d(geom = "point", 
                  aes(size = after_stat(density), color = after_stat(density)), 
                  n = 5, contour = FALSE) +
  scale_color_gradient(low = "lightblue", high = "darkblue") +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

df %>% ggplot(aes(easy, overall)) +
  geom_count(aes(size = ..n.., color = ..n..)) +
  scale_color_gradient(low = "lightblue", high = "darkblue") +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

dflm <- lm(easy ~ overall, data = df)

dflm %>% pander()

par(mfrow = c(1,3))
plot(dflm, which = 1:2)
plot(dflm$residuals)


```

```{r}
log <- clean %>% 
  filter(rWouldTakeAgain != "N/A") %>% 
  mutate(
    rWouldTakeAgain = ifelse(rWouldTakeAgain == "Yes", 1, 0)
  ) 

log %>% ggplot(aes(rEasy, rWouldTakeAgain)) +
  geom_point(aes(color = as.character(rWouldTakeAgain))) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE, color = "black")

glm <- glm(rWouldTakeAgain ~ rOverall, data = log, family = binomial)
glm %>% pander()
hoslem.test(glm$y, glm$fitted, g = 10) %>% pander()
```

### Wilcoxon

```{r}
glimpse(prof)

# only two institutions
  # sociology, math
# 
profwil <- prof %>% 
  filter(tDept %in% c("Mathematical and Computer Sci.", "Sociology"), 
         overall_rating > 0)

wilcox.test(as.numeric(overall_rating) ~ tDept, data = profwil)

prof$tDept %>% unique()
```
